name: Website Monitor

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check website
        id: sitecheck
        env:
          URL: https://yourdomain.com/2222222
        run: |
          STATUS=$(curl -L -s -o /tmp/site.html -w "%{http_code}" --max-time 20 "$URL" || echo "000")
          echo "Status: $STATUS"
          echo "status=$STATUS" >> "$GITHUB_OUTPUT"

      - name: Send Telegram if site is down
        if: steps.sitecheck.outputs.status != '200'
        run: |
          MSG="🚨 Website DOWN
          URL: https://yourdomain.com/2222222
          Status: ${{ steps.sitecheck.outputs.status }}"

          curl -s -X POST "https://api.telegram.org/bot8588516671:AAFrmypc4_3jEkiXc-CTZ3WV7mwJmQSRxhk/sendMessage" \
            -d "chat_id=615992515" \
            --data-urlencode "text=$MSG"

      - name: Fail job if site is down
        if: steps.sitecheck.outputs.status != '200'
        run: exit 1
